#!/bin/sh
if [ -z $1 ]
then
	echo "Usage: clone [github_username/gist_id]"
	exit
fi

NAME=`echo $1 | sed -e 's#\([^/]*\)/.*#\1#g'`
ID=`echo $1 | sed -e 's#[^/]*/\(.*\)#\1#g'`

git clone ssh://git@gist.github.com/$ID
DESC=`cat $ID/README.md | sed -e 's/# \(.*\)/\1/g'`
DESC_=`echo $DESC | sed -e 's/ /-/g'`
mv $ID/ $DESC_/
cp template/.* template/* $DESC_/
sed -e 's/_____/'"$DESC"'/' -e 's/gist_id/'"$ID"'/' -e 's/__name__/'"$NAME"'/g' -i $DESC_/README.md 